### ISSUE TITLE
iter_size

### ISSUE THREAD

**Issue by wzj5133329** [yewuyue111/Mobileface-caffe#2]
你好，因为这个参数之前用的比较少，也是看了您的这个项目才知道，我在网上查了相关资料，caffe官方并没有这个参数的说明，我的问题是，如果设置这个参数相当于调整了batch_size,那么迭代次数是不是应该减少呢，因为我设置了这个参数为n后，训练的速度相应的变慢了n倍

**Comment by deepage** [comment]
@wzj5133329 其实你看代码的话就可以很清楚了，这个参数的目的是把iter_size次数的loss加起来（你可以想象成多个GPU，每个上面单独算loss，然后再汇总，作为总的Loss），只不过这里是得等上一个batch_size的数据算完，直到所有iter_size都算完才开始更新权重，也就是才过了一次迭代。这也就是为什么你的训练速度会慢。多GPU训练时，数据是并行计算的，而这里是串行计算，所有iter_size设为多少，训练就会慢多少倍。

**Comment by wzj5133329** [comment]
谢谢解答，懂了。。。
